version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: stream_web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - stream_net

  db:
    image: mysql:8.0
    container_name: stream_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: streamsite
      MYSQL_USER: streamuser
      MYSQL_PASSWORD: streampass
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stream_net

  adminer:
    image: adminer
    container_name: stream_adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - stream_net

volumes:
  db_data:

networks:
  stream_net:
